FROM centos:7

RUN yum install -y gcc systemtap yum-utils
ENV KERNEL KERNELVERSION
RUN yum install -y kernel-${KERNEL} kernel-devel-${KERNEL}
RUN debuginfo-install -y kernel-${KERNEL}

WORKDIR /ioriot
ADD ./ /ioriot
RUN mkdir -p /opt/ioriot
VOLUME /opt
